## The chart API version
apiVersion: v1
name: techtrends 
## A single-sentence description of this project
description: Restful python flask app exposing conf content
## A list of keywords about this project to quickly identify the chart's capabilities.
keywords:
- techtrends
## The chart version, here set to `3.7.0`
version: 1.0.0
## List of maintainers, their names, and method of contact
maintainers:
- name: rudi 
  email: rudi.grasmuck@gmail.com
