## provide the name of the namespace
namespace:
  name: staging
  
service:
  port: 5111
 
## set the number of replicas for an application 
replicaCount: 3

resources:
  requests:
    memory: 90Mi
    CPU: 300m
  limits:
    memory: 128Mi
    CPU: 500m
